"""set weekday all to small characters

Revision ID: 1446abed5106
Revises: 309693f924f8
Create Date: 2020-02-03 05:34:01.616544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1446abed5106'
down_revision = '309693f924f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('friday', sa.Boolean(), nullable=True))
    op.add_column('dishes', sa.Column('monday', sa.Boolean(), nullable=True))
    op.add_column('dishes', sa.Column('saturday', sa.Boolean(), nullable=True))
    op.add_column('dishes', sa.Column('sunday', sa.Boolean(), nullable=True))
    op.add_column('dishes', sa.Column('thursday', sa.Boolean(), nullable=True))
    op.add_column('dishes', sa.Column('tuesday', sa.Boolean(), nullable=True))
    op.add_column('dishes', sa.Column('wednesday', sa.Boolean(), nullable=True))
    op.drop_column('dishes', 'Monday')
    op.drop_column('dishes', 'Tuesday')
    op.drop_column('dishes', 'Friday')
    op.drop_column('dishes', 'Wednesday')
    op.drop_column('dishes', 'Thursday')
    op.drop_column('dishes', 'Sunday')
    op.drop_column('dishes', 'Saturday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('Saturday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('Sunday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('Thursday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('Wednesday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('Friday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('Tuesday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('Monday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('dishes', 'wednesday')
    op.drop_column('dishes', 'tuesday')
    op.drop_column('dishes', 'thursday')
    op.drop_column('dishes', 'sunday')
    op.drop_column('dishes', 'saturday')
    op.drop_column('dishes', 'monday')
    op.drop_column('dishes', 'friday')
    # ### end Alembic commands ###
