"""drop duplicated pk index

Revision ID: 29cf08419238
Revises: e9afa676cda0
Create Date: 2020-01-14 01:42:59.116258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cf08419238'
down_revision = 'e9afa676cda0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deposits_id', table_name='deposits')
    op.drop_index('ix_dishes_id', table_name='dishes')
    op.drop_index('ix_orders_id', table_name='orders')
    op.drop_index('ix_restaurants_id', table_name='restaurants')
    op.drop_index('ix_spots_id', table_name='spots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_spots_id', 'spots', ['id'], unique=False)
    op.create_index('ix_restaurants_id', 'restaurants', ['id'], unique=False)
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.create_index('ix_dishes_id', 'dishes', ['id'], unique=False)
    op.create_index('ix_deposits_id', 'deposits', ['id'], unique=False)
    # ### end Alembic commands ###
