"""add 'in_use' attribute to spot

Revision ID: 2b61a6b8c238
Revises: a7f52c56f415
Create Date: 2020-01-13 12:30:05.289729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b61a6b8c238'
down_revision = 'a7f52c56f415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('in_used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'in_used')
    # ### end Alembic commands ###
