"""add 'info' column  to restaurants

Revision ID: 2ed033004183
Revises: df307d35b2e5
Create Date: 2020-01-13 00:48:50.786710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed033004183'
down_revision = 'df307d35b2e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'info')
    # ### end Alembic commands ###
