"""add not nullable to original_price and price_sold
  drop column time in order

Revision ID: 38e8350c2bd1
Revises: 29cf08419238
Create Date: 2020-01-14 02:39:33.285237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38e8350c2bd1'
down_revision = '29cf08419238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'original_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'price_sold',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('orders', 'price_sold',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'original_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
