"""add in_use to route model

Revision ID: 7a3ef66133a4
Revises: e77b37ca230f
Create Date: 2020-02-14 18:20:54.902572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3ef66133a4'
down_revision = 'e77b37ca230f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('in_use', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'in_use')
    # ### end Alembic commands ###
