"""set foreignkey route in restaurant not nullable

Revision ID: 8bc51c06f4b9
Revises: 7a3ef66133a4
Create Date: 2020-02-14 18:47:51.406135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc51c06f4b9'
down_revision = '7a3ef66133a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
