"""add variable Order.YesterdayMaxID

Revision ID: 9b462789956c
Revises: 91ffe8dcdb49
Create Date: 2020-01-14 21:03:06.126615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b462789956c'
down_revision = '91ffe8dcdb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'original_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'price_sold',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'spot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'orders', 'spots', ['spot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'spot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'price_sold',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'original_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
