"""change 'in_used' attribute to 'in_use'

Revision ID: 9f55679b95ee
Revises: 2b61a6b8c238
Create Date: 2020-01-13 12:34:42.477134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f55679b95ee'
down_revision = '2b61a6b8c238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('in_use', sa.Boolean(), nullable=True))
    op.drop_column('spots', 'in_used')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('in_used', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('spots', 'in_use')
    # ### end Alembic commands ###
