"""add 'in_cooperation' column to restaurants

Revision ID: a7f52c56f415
Revises: 2ed033004183
Create Date: 2020-01-13 00:57:52.222356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f52c56f415'
down_revision = '2ed033004183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('in_cooperation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'in_cooperation')
    # ### end Alembic commands ###
