"""add original_price to order

Revision ID: ccb6e9fbb3a8
Revises: 9f55679b95ee
Create Date: 2020-01-14 01:35:13.166613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb6e9fbb3a8'
down_revision = '9f55679b95ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('original_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'original_price')
    # ### end Alembic commands ###
