"""add restaurant_url to restaurant model

Revision ID: d994ed01cbdd
Revises: 1446abed5106
Create Date: 2020-02-04 14:07:26.486749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd994ed01cbdd'
down_revision = '1446abed5106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('restaurant_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'restaurant_url')
    # ### end Alembic commands ###
