"""update several columns in dishes. 
    add foreign key from orders to spots

Revision ID: df307d35b2e5
Revises: 13c0da625f2d
Create Date: 2020-01-12 22:54:56.982191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df307d35b2e5'
down_revision = '13c0da625f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('in_supply', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_dishes_stock'), 'dishes', ['stock'], unique=False)
    op.drop_column('dishes', 'updated_at')
    op.drop_column('dishes', 'show')
    op.add_column('orders', sa.Column('spot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'spots', ['spot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'spot_id')
    op.add_column('dishes', sa.Column('show', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_dishes_stock'), table_name='dishes')
    op.drop_column('dishes', 'in_supply')
    # ### end Alembic commands ###
