"""add index on order.created_at

Revision ID: e1386595bc32
Revises: 9b462789956c
Create Date: 2020-01-14 22:42:28.785260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1386595bc32'
down_revision = '9b462789956c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    # ### end Alembic commands ###
