"""add explanation attributes for negative top up

Revision ID: e49deb4b961a
Revises: e1386595bc32
Create Date: 2020-02-01 01:14:36.130843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49deb4b961a'
down_revision = 'e1386595bc32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposits', 'explanation')
    # ### end Alembic commands ###
